#!/bin/sh
#
# Yet Another RSync bAckup (yarsa)
# Copyright (C) 2013 Enrico Rossi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This package is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

# Default configuration
# todo: link to the git describe --tags
VERSION="1.0"
PATH=$PATH:/sbin:/bin:/usr/sbin:/usr/bin
DATUM=$(date +%y%m%d%H%M)
RSYNC_SWITCH="-av --delete --delete-excluded --ignore-errors --whole-file --numeric-ids"

# Check if the number of backups > 0
check_cycle()
{
    echo -n "Keep old backup: "

    if [ $count -gt 0 ]; then
        echo "$count"
    else
        echo "Error, wrong number $count"
        exit 1
    fi
}

# Check the destination directory.
check_dest()
{
    echo -n "Backup to: "

    if [ -d "$dest" ]; then
        echo "$dest"
    else
        echo "Error $dest not found."
        exit 1
    fi
}

# Check the source directory.
check_source()
{
    echo -n "Source: "

    if [ -d "$source" ]; then
        echo "$source"
    else
        echo "Error $source not found."
        exit 1
    fi
}

# Check if the last directory to be linked exists.
check_lastlink()
{
    echo -n "Last backup to be linked: "

    if [ -d "$last_to_link" ]; then
        echo "$last_to_link"
    else
        echo "Error $last_to_link not found."
        exit 1
    fi
}

# Check if the new backup does not already exists.
check_newlink()
{
    echo -n "New backup: "

    if [ ! -e $new_to_link ]; then
        echo "$new_to_link"
    else
        echo "Error, $new_to_link already exists!."
        exit 1
    fi
}

# Perform safety checks before starting the backup.
do_checks()
{
    # Why check the source???
#    if [ ! $rotateonly ]; then
#        check_source
#    fi

    check_dest
    check_cycle
    check_lastlink
    check_newlink
}

# List all backup's directory found.
list_backup_dir()
{
    echo "backup directory found: $backup_number"

    for i in $backup_list; do
        echo " " $i
    done
}

# List the backup's directory to be removed.
list_rm_dir()
{
    echo "directory to remove: $remove_number"

    for i in $remove_list; do
        echo " " $i
    done
}

remove_old_backups()
{
    for i in $remove_list; do
        echo -n "Removing ... $i ... ["

        if [ -d $i ]; then
            rm -rf $i
            echo "OK]"
        else
            echo "FAILED]"
            exit 2
        fi
    done
}

link_new_dir()
{
    echo -n "Hard linking $new_to_link to $last_to_link ... ["

    if [ -d $last_to_link ]; then
        cp -al $last_to_link $new_to_link
        echo "OK]"
    else
        echo "FAILED]"
        exit 3
    fi
}

# Echo the df -m
dodf()
{
    if [ $dodf ]; then
        echo
        echo "-- df -m --"
        df -m
    fi
}

# execute the sync
do_backup()
{
    # add the exclude/include files if present.
    if [ -f $excludefile ]; then
        RSYNC_SWITCH="$RSYNC_SWITCH --exclude-from=$excludefile"
    fi

    if [ -f $includefile ]; then
        RSYNC_SWITCH="$RSYNC_SWITCH --include-from=$includefile"
    fi

    echo "rsync $RSYNC_SWITCH $source $new_to_link/ 2>&1"
    echo
    rsync $RSYNC_SWITCH $source $new_to_link/ 2>&1
    echo
    echo " * Completed *"
}

# Help message
usage()
{
    echo "Usage: $prog [-h] [-c cycle] [-d date] [-f] [-l] [-r] [-s SRC] [-t] DEST"
    echo " or    $prog [-R] [-c cycle] [-f] [-t]"
    echo
    echo "Options"
    echo " -c cycle - save cycle versions (default: 7)"
    echo " -d date  - link to the date instead of the current time"
    echo " -f       - log df space before and after"
    echo " -l       - create log files"
    echo " -r       - just roll, don't sync"
    echo " -R       - assume rsyncd remote call"
    echo " -s src   - source directory"
    echo " -t       - create backup directory"
    echo " -h       - this help"
}

## Main
# parse args
prog=$(basename $0)
count=7
dodf=
log=
logfile=
remote=
rolldate=
rotateonly=
createdir=

while getopts c:dlr:Rs:th opt; do
    case "$opt" in
        c) count="$OPTARG"
            ;;
        d) rolldate="$OPTARG"
            ;;
        f) dodf=1
            ;;
        l) log=1
            ;;
        r) rotateonly=1
            ;;
        R) remote=1
            ;;
        s) source="$OPTARG"
            ;;
        t) createdir=1
            echo "- touch not implemented -"
            exit 1
            ;;
        h) usage
            exit 0
            ;;
        *) usage
            exit 1
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ $remote ]; then
    dest=$RSYNC_MODULE_PATH
    rotateonly=1
    rolldate=$(basename $RSYNC_REQUEST)
    source="* REMOTE *"
    log=1
    #echo $RSYNC_MODULE_NAME
    #echo $RSYNC_HOST_ADDR
    #echo $RSYNC_HOST_NAME
    #echo $RSYNC_USER_NAME
    #echo $RSYNC_PID
    #echo $RSYNC_ARG#
elif [ $# -eq 0 ] || [ $# -gt 1 ]; then
    usage
    exit 1
else
    dest=$1
    # Non valid in remote
    excludefile=$dest/yarsa.exclude
    includefile=$dest/yarsa.include
fi

configfile=$dest/yarsa.cfg

# first log the status
echo "Yarsa backup system ($VERSION)"
echo
echo "start at $(date)"

# Read the local conffile
if [ -r "$configfile" ]; then
    . $configfile
else
    echo " Missing config file: $configfile"
    exit 1
fi

backup_number=$(find $dest -maxdepth 1 -type d -name "rsb_*" | wc -l)
backup_list=$(find $dest -maxdepth 1 -type d -name "rsb_*" | sort)

# Directory to remove
remove_number=$(($backup_number - $count))

# Create a list of dir to remove like:
if [ $remove_number -gt 0 ]; then
    remove_list=$(find $dest -maxdepth 1 -type d -name "rsb_*"|sort|head -$remove_number)
fi

# The most recent backups
last_to_link=$(find $dest -maxdepth 1 -type d -name "rsb_*"|sort|tail -1)

# The new backups to create
if [ $rolldate ]; then
    new_to_link=$dest/$rolldate
else
    new_to_link=$dest/rsb_$DATUM
fi

do_checks
list_backup_dir
list_rm_dir
dodf
remove_old_backups
link_new_dir
echo

if [ ! $rotateonly ]; then
    do_backup
else
    echo "Rotate only active, skipping backup."
fi

dodf
echo
echo "end at $(date)"

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
